const env = {
  AUTH_SECRET: process.env.AUTH_SECRET as string,
  AUTH_FIREBASE_CLIENT_EMAIL: process.env.AUTH_FIREBASE_CLIENT_EMAIL as string,
  AUTH_FIREBASE_PRIVATE_KEY: process.env.AUTH_FIREBASE_PRIVATE_KEY as string,
  AUTH_GITHUB_SECRET: process.env.AUTH_GITHUB_SECRET as string,
  AUTH_GITHUB_ID: process.env.AUTH_GITHUB_ID as string,
  AUTH_FIREBASE_PROJECT_ID: process.env.AUTH_FIREBASE_PROJECT_ID as string,
  AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET as string,
  AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID as string,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env
    .NEXT_PUBLIC_FIREBASE_PROJECT_ID as string,
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env
    .NEXT_PUBLIC_FIREBASE_API_KEY as string,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env
    .NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN as string,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env
    .NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET as string,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env
    .NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID as string,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env
    .NEXT_PUBLIC_FIREBASE_APP_ID as string,
};

if (
  !env.AUTH_SECRET ||
  !env.AUTH_FIREBASE_PROJECT_ID ||
  !env.AUTH_FIREBASE_CLIENT_EMAIL ||
  !env.AUTH_FIREBASE_PRIVATE_KEY ||
  !env.AUTH_GITHUB_SECRET ||
  !env.AUTH_GITHUB_ID ||
  !env.AUTH_GOOGLE_SECRET ||
  !env.AUTH_GOOGLE_ID ||
  !env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ||
  !env.NEXT_PUBLIC_FIREBASE_API_KEY ||
  !env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ||
  !env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ||
  !env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ||
  !env.NEXT_PUBLIC_FIREBASE_APP_ID
) {
  throw new Error("Missing environment variables");
}

export default env;
