interface ClientEnv {
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
  NEXT_PUBLIC_FIREBASE_API_KEY: string;
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
  NEXT_PUBLIC_FIREBASE_APP_ID: string;
  NEXT_PUBLIC_SERVER_API_URL: string;
}

const clientEnv: ClientEnv = {
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env
    .NEXT_PUBLIC_FIREBASE_PROJECT_ID as string,
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env
    .NEXT_PUBLIC_FIREBASE_API_KEY as string,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env
    .NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN as string,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env
    .NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET as string,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env
    .NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID as string,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env
    .NEXT_PUBLIC_FIREBASE_APP_ID as string,
  NEXT_PUBLIC_SERVER_API_URL: process.env.NEXT_PUBLIC_SERVER_API_URL as string,
};

if (
  !clientEnv.NEXT_PUBLIC_FIREBASE_PROJECT_ID ||
  !clientEnv.NEXT_PUBLIC_FIREBASE_API_KEY ||
  !clientEnv.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ||
  !clientEnv.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ||
  !clientEnv.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ||
  !clientEnv.NEXT_PUBLIC_FIREBASE_APP_ID ||
  !clientEnv.NEXT_PUBLIC_SERVER_API_URL
) {
  throw new Error("Missing client-side environment variables");
}

export default clientEnv;
