services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - lama-cleaner
    volumes:
      - ./server/uploads:/app/uploads
    environment:
      - LAMA_CLEANER_URL=http://lama-cleaner:8080/inpaint

  lama-cleaner:
    build:
      context: ./server/lama-cleaner
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./lama-cleaner/models:/root/.cache
