name: "Standard Python steps"

description: "Runs the standard steps for Python"

inputs:
  NODE_VERSION:
    required: true
    description: "The version of the Python to use"
    default: "3.12"

runs:
  using: "composite"
  steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.NODE_VERSION}}

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('server/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: |
        cd server
        pip install -r requirements.txt
