name: Deploy Server & Lama Cleaner to Railway
run-name: "🚛 CD: Deploy Artifacts (${{ github.event.inputs.ref }}) to Railway"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref to deploy"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    environment: production
    container:
      image: ghcr.io/railwayapp/cli:3.21.0
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Main Server to Railway
        run: |
          cd server
          railway up --service=${{ vars.RAILWAY_SERVER_SERVICE_NAME }} --verbose

      - name: Deploy Lama Cleaner to Railway
        run: |
          cd server/lama-cleaner
          railway up --service=${{ vars.RAILWAY_LAMA_CLEANER_SERVICE_NAME }} --verbose
