name: Deploy Next.js to Vercel & Server to Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          cd client
          vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

  # VERSION 2
  # RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
  # RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  deploy-server:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:3.21.0
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    env:
      RAILWAY_TOKEN: 8438468e-e8b1-4c0d-9d4d-84cdde7a7f9e
      SERVER_SERVICE: server
      LAMA_CLEANER_SERVICE: lama-cleaner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Railway Status
        run: railway status

      - name: Deploy Main Server to Railway
        run: |
          cd server
          pwd
          railway up --service=${{ env.SERVER_SERVICE }} --verbose

      - name: Deploy Lama Cleaner to Railway
        run: |
          cd server/lama-cleaner
          railway up --service=${{ env.LAMA_CLEANER_SERVICE }} --verbose
