name: Deploy Next.js to Vercel & Server to Railway

on:
  push:
    branches:
      - main
  # pull_request:

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          cd client
          vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

  deploy-server:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install Railway CLI
      #   run: curl -fsSL cli.new | sh

      - name: Deploy Server to Railway
        run: |
          cd server
          railway up --service server -- --project ${{ secrets.RAILWAY_PROJECT_ID }} --environment ${{ secrets.RAILWAY_ENVIRONMENT_ID }}

      - name: Deploy Lama Cleaner to Railway
        run: |
          cd server
          railway up --service lama-cleaner -- --project ${{ secrets.RAILWAY_PROJECT_ID }} --environment ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
