name: Deploy Next.js to Vercel & Server to Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_server:
        description: 'Deploy server to Railway (true/false)'
        required: false
        default: true
        type: boolean

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          cd client
          vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  deploy-server:
    if: github.event_name != 'workflow_dispatch' || inputs.deploy_server == 'true'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:3.21.0
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SERVER_SERVICE: server
      LAMA_CLEANER_SERVICE: lama-cleaner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Main Server to Railway
        run: |
          cd server
          railway up --service=${{ env.SERVER_SERVICE }} --verbose

      - name: Deploy Lama Cleaner to Railway
        run: |
          cd server/lama-cleaner
          railway up --service=${{ env.LAMA_CLEANER_SERVICE }} --verbose
