name: Deploy Next.js to Vercel & Server to Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # deploy-client:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install Vercel CLI
  #       run: npm install -g vercel

  #     - name: Deploy to Vercel
  #       run: |
  #         cd client
  #         vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

  # deploy-server:
  #   runs-on: ubuntu-latest
  #   env:
  #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  #     SERVER_SERVICE: server
  #     LAMA_CLEANER_SERVICE: lama-cleaner
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Install Railway CLI
  #       run: npm install -g @railway/cli

  #     - name: Verify Railway Authentication
  #       run: railway whoami
  #       env:
  #         RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  #     - name: Deploy Main Server to Railway
  #       run: |
  #         cd server
  #         railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ env.SERVER_SERVICE }}
  #         railway up
  #       env:
  #         RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  #     - name: Deploy Lama Cleaner to Railway
  #       run: |
  #         cd server/lama-cleaner
  #         railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ env.LAMA_CLEANER_SERVICE }}
  #         railway up
  #       env:
  #         RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}


  # VERSION 1
  # deploy-server:
  #   runs-on: ubuntu-latest
  #   container: 
  #     image: ghcr.io/railwayapp/cli:latest
  #     env:
  #       RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  #   env:
  #     SERVER: server
  #     LAMA_CLEANER: lama-cleaner
  #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Verify Railway Authentication
  #       run: railway status

  #     - name: Deploy Server to Railway
  #       run: |
  #         cd server
  #         export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
  #         railway link --project=${{ secrets.RAILWAY_PROJECT_ID }}
  #         railway up --service=${{ env.SERVER }}

  #     - name: Deploy Lama Cleaner to Railway
  #       run: |
  #         cd server
  #         export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
  #         railway link --project=${{ secrets.RAILWAY_PROJECT_ID }}
  #         railway up --service=${{ env.LAMA_CLEANER }}


  # VERSION 2
        # RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
              # RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  deploy-server:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:3.21.0
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    env:
      RAILWAY_TOKEN: 8438468e-e8b1-4c0d-9d4d-84cdde7a7f9e
      SERVER_SERVICE: server
      LAMA_CLEANER_SERVICE: lama-cleaner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Railway Status
        run: railway status

      - name: Verify Railway Authentication
        run: railway whoami --token ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Deploy Main Server to Railway
        run: |
          cd server
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ env.SERVER_SERVICE }}
          railway up

      - name: Deploy Lama Cleaner to Railway
        run: |
          cd server/lama-cleaner
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ env.LAMA_CLEANER_SERVICE }}
          railway up
